### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by InfernalAzazel** [thewh1teagle/tauric#1]
How will tauri plugins be solved in the future? Do we need to write C interfaces for all of them?

**Comment by thewh1teagle** [comment]
> How will tauri plugins be solved in the future? Do we need to write C interfaces for all of them?

Thanks! I think we’ll need to create C interfaces for the plugins as well. The plugins must match the version of Tauri; otherwise, things will break. It will be useful to write the plugins as shared libraries that accept a Tauri app handle pointer. This way, we can easily load plugins just by collecting shared library files without needing to compile anything.

**Comment by InfernalAzazel** [comment]
This workload is significant and relies on special versions of Tauri.
I have tried to directly implement the type tauri in Python before, but after observing the Python ecosystem, I found that there are not many ready-made technologies, and the workload is huge. Moreover, I do not have many events related to open source

Python attempts to implement frameworks similar to Tauri
